Repository HybridPlanner/backend, pull requests merged in 2023-10, with the labels that each got.

#32 Rainbow bubble management
  src/services/rainbow/rainbow.service.ts
Labels: enhancement

#34 feat: disable auth and allow to search meeting prior a date
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.module.ts
  src/meetings/dto/create-meeting.dto.ts
  src/meetings/meetings.controller.ts
  src/meetings/meetings.service.ts
Labels: enhancement

#37 fix: find meetings not searching with timestamp as expected
  src/meetings/dto/create-meeting.dto.ts
  src/meetings/meetings.controller.ts
  src/meetings/meetings.service.ts
  tsconfig.json
Labels: bug

#38 docs: add how-to for docker utilisation in readme file
  README.md
Labels: documentation

#39 feat: add description field to meeting
  prisma/migrations/20231026124252_replace_date_with_start_date_and_end_date/migration.sql
  prisma/migrations/20231026125334_add_meeting_description_field/migration.sql
  prisma/schema.prisma
  src/meetings/dto/create-meeting.dto.ts
  src/meetings/meetings.service.ts
Labels: enhancement
